const data = [
  {
    count: 150,
    totalCount: 2127,
    page: 2,
    totalPages: 15,
    lastItemIndex: 300,
    results: [
      {
        _id: "fwMKi2Q0Pk",
        author: "Michael Phelps",
        content:
          "You can't put a limit on anything. The more you dream, the farther you get.",
        tags: ["Sports", "Competition"],
        authorSlug: "michael-phelps",
        length: 75,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "nH5op9VWSA5",
        author: "Confucius",
        content:
          "The superior man understands what is right; the inferior man understands what will sell.",
        tags: ["Business"],
        authorSlug: "confucius",
        length: 88,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "py0SqUMHGW9",
        author: "Howard H. Aiken",
        content:
          "Don't worry about people stealing your ideas. If your ideas are any good, you'll have to ram them down people's throats.",
        tags: ["Business"],
        authorSlug: "howard-h-aiken",
        length: 120,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "gZMl2CrQvRQ",
        author: "Ted Williams",
        content:
          "Baseball is the only field of endeavor where a man can succeed three times out of ten and be considered a good performer.",
        tags: ["Sports", "Competition"],
        authorSlug: "ted-williams",
        length: 121,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "3KGpfidF22D",
        author: "William James",
        content:
          "Most people never run far enough on their first wind to find out they've got a second.",
        tags: ["Sports", "Competition"],
        authorSlug: "william-james",
        length: 86,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "FGh99twyFY",
        author: "John F. Kennedy",
        content: "Things do not happen. Things are made to happen.",
        tags: ["Motivational"],
        authorSlug: "john-f-kennedy",
        length: 48,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "S78ad3jDcyA",
        author: "John Madden",
        content:
          "The fewer rules a coach has, the fewer rules there are for players to break.",
        tags: ["Sports", "Competition"],
        authorSlug: "john-madden",
        length: 76,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "qKv9nrdgS0M",
        author: "Kyle Chandler",
        content:
          "Opportunity does not knock, it presents itself when you beat down the door.",
        tags: ["Motivational"],
        authorSlug: "kyle-chandler",
        length: 75,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "uPuUG-KkA",
        author: "Mark Twain",
        content:
          "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
        tags: ["Business"],
        authorSlug: "mark-twain",
        length: 88,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "lpxXplIA4ie",
        author: "Yogi Berra",
        content: "Half the lies they tell about me aren't true.",
        tags: ["Sports", "Competition"],
        authorSlug: "yogi-berra",
        length: 45,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "x-0qEVIZ66n",
        author: "Eric Liddell",
        content: "God made me fast. And when I run, I feel His pleasure.",
        tags: ["Sports", "Competition"],
        authorSlug: "eric-liddell",
        length: 54,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "-5LundE5jXD",
        author: "Erma Bombeck",
        content:
          "If a man watches three football games in a row, he should be declared legally dead.",
        tags: ["Sports", "Humorous"],
        authorSlug: "erma-bombeck",
        length: 83,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Zrxblk3MazL",
        author: "John Kenneth Galbraith",
        content:
          "Meetings are indispensable when you don't want to do anything.",
        tags: ["Business"],
        authorSlug: "john-kenneth-galbraith",
        length: 62,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "2wnTElJ9STU",
        author: "Hank Aaron",
        content:
          "My motto was always to keep swinging. Whether I was in a slump or feeling badly or having trouble off the field, the only thing to do was keep swinging.",
        tags: ["Sports", "Competition"],
        authorSlug: "hank-aaron",
        length: 152,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "x1ekufax6w",
        author: "Jeff Bezos",
        content:
          "A brand for a company is like a reputation for a person. You earn reputation by trying to do hard things well.",
        tags: ["Business"],
        authorSlug: "jeff-bezos",
        length: 110,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "r7qJ-YKIq2e",
        author: "Earl Monroe",
        content:
          "Just be patient. Let the game come to you. Don't rush. Be quick, but don't hurry.",
        tags: ["Sports", "Competition"],
        authorSlug: "earl-monroe",
        length: 81,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "1gJ03696_R",
        author: "Benjamin Disraeli",
        content: "Never complain and never explain.",
        tags: ["Motivational"],
        authorSlug: "benjamin-disraeli",
        length: 33,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "MsGmNTCtAXd",
        author: "Mike Singletary (basketball)",
        content:
          "Do you know what my favorite part of the game is? The opportunity to play.",
        tags: ["Sports", "Competition"],
        authorSlug: "mike-singletary-basketball",
        length: 74,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "y1iv94PsONA",
        author: "Edward Gibbon",
        content: "Our work is the presentation of our capabilities.",
        tags: ["Business"],
        authorSlug: "edward-gibbon",
        length: 49,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "E_uIJ03GjDQ",
        author: "André Malraux",
        content: "To command is to serve, nothing more and nothing less.",
        tags: ["Business"],
        authorSlug: "andre-malraux",
        length: 54,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "WPXF6M0Yn_Y",
        author: "Warren Bennis",
        content:
          "Trust is the lubrication that makes it possible for organizations to work.",
        tags: ["Business"],
        authorSlug: "warren-bennis",
        length: 74,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "xYHasPkPjV7",
        author: "Robert Griffin III",
        content:
          "Football is football and talent is talent. But the mindset of your team makes all the difference.",
        tags: ["Sports", "Competition"],
        authorSlug: "robert-griffin-iii",
        length: 97,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "bcHXRb64gZH",
        author: "Heywood Broun",
        content: "Sports do not build character. They reveal it.",
        tags: ["Sports", "Competition"],
        authorSlug: "heywood-broun",
        length: 46,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "_WfHG0pIS0",
        author: "W. Clement Stone",
        content: "Aim for the moon. If you miss, you may hit a star.",
        tags: ["Motivational"],
        authorSlug: "w-clement-stone",
        length: 50,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "mdzzSdP_dF",
        author: "Colin Powell",
        content:
          "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
        tags: ["Success"],
        authorSlug: "colin-powell",
        length: 103,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "trKnEw-ZVY",
        author: "Ralph Marston",
        content: "What you do today can improve all your tomorrows.",
        tags: ["Motivational"],
        authorSlug: "ralph-marston",
        length: 49,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "eAwQS0LKTIk",
        author: "William Blake",
        content: "No bird soars too high if he soars with his own wings.",
        tags: ["Motivational"],
        authorSlug: "william-blake",
        length: 54,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "boO8cxCyUZ",
        author: "Sam Walton",
        content:
          "There is only one boss. The customer. And he can fire everybody in the company from the chairman on down, simply by spending his money somewhere else.",
        tags: ["Business"],
        authorSlug: "sam-walton",
        length: 150,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "lTm3ZNHDrh7",
        author: "Bob Knight",
        content:
          "You don't play against opponents, you play against the game of basketball.",
        tags: ["Sports", "Competition"],
        authorSlug: "bob-knight",
        length: 74,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "SnxKyCAPxV",
        author: "Tom Brokaw",
        content:
          "It's easy to make a buck. It's a lot tougher to make a difference.",
        tags: ["Business"],
        authorSlug: "tom-brokaw",
        length: 66,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Hpo_qh-q76A",
        author: "Reggie Jackson (basketball, born 1990)",
        content: "Fans don't boo nobodies.",
        tags: ["Sports", "Competition"],
        authorSlug: "reggie-jackson-basketball-born-1990",
        length: 24,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "EqK6-7vPt",
        author: "Elon Musk",
        content:
          "When something is important enough, you do it even if the odds are not in your favor.",
        tags: ["Motivational"],
        authorSlug: "elon-musk",
        length: 85,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "u88FH0TrZCH",
        author: "Thomas Jefferson",
        content:
          "I hope we shall crush in its birth the aristocracy of our monied corporations which dare already to challenge our government to a trial by strength, and bid defiance to the laws of our country.",
        tags: ["Business"],
        authorSlug: "thomas-jefferson",
        length: 193,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Gtt0T3mfPbx",
        author: "Billie Jean King",
        content: "Champions keep playing until they get it right.",
        tags: ["Sports", "Competition"],
        authorSlug: "billie-jean-king",
        length: 47,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "1mFyxKntETm",
        author: "Ayn Rand",
        content:
          "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
        tags: ["Motivational"],
        authorSlug: "ayn-rand",
        length: 87,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "yq5LCWQjDJU",
        author: "Niccolò Machiavelli",
        content:
          "No enterprise is more likely to succeed than one concealed from the enemy until it is ripe for execution.",
        tags: ["Business"],
        authorSlug: "niccolo-machiavelli",
        length: 105,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "UN97SbNn3N",
        author: "Ambrose Bierce",
        content:
          "The gambling known as business looks with austere disfavor upon the business known as gambling.",
        tags: ["Business"],
        authorSlug: "ambrose-bierce",
        length: 95,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "JRmne2RXYn",
        author: "Henry David Thoreau",
        content:
          "Many men go fishing all of their lives without knowing that it is not fish they are after.",
        tags: ["Sports", "Competition"],
        authorSlug: "henry-david-thoreau",
        length: 90,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "wNd1PnDiIN",
        author: "Bob Feller",
        content:
          "Every day is a new opportunity. You can build on yesterday's success or put its failures behind and start over again. That's the way life is, with a new game every day, and that's the way baseball is.",
        tags: ["Sports", "Competition"],
        authorSlug: "bob-feller",
        length: 200,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "0Ny0rPtnM3",
        author: "Vince Lombardi",
        content: "Winners never quit and quitters never win.",
        tags: ["Sports", "Competition"],
        authorSlug: "vince-lombardi",
        length: 42,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "vtzyn3LKIA",
        author: "Wayne Gretzky",
        content:
          "A good hockey player plays where the puck is. A great hockey player plays where the puck is going to be.",
        tags: ["Sports", "Competition"],
        authorSlug: "wayne-gretzky",
        length: 104,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "l0LfTgApB3",
        author: "Babe Ruth",
        content:
          "The way a team plays as a whole determines its success. You may have the greatest bunch of individual stars in the world, but if they don't play together, the club won't be worth a dime.",
        tags: ["Sports", "Competition"],
        authorSlug: "babe-ruth",
        length: 186,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "nYm8bumyc0E",
        author: "Babe Ruth",
        content: "You just can't beat the person who never gives up.",
        tags: ["Motivational"],
        authorSlug: "babe-ruth",
        length: 50,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "AxNf6c-G_KI",
        author: "Rogers Hornsby",
        content:
          "People ask me what I do in winter when there's no baseball. I'll tell you what I do. I stare out the window and wait for spring.",
        tags: ["Sports", "Competition"],
        authorSlug: "rogers-hornsby",
        length: 128,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "RiULc-0Ak0",
        author: "Peter Drucker",
        content:
          "The entrepreneur always searches for change, responds to it, and exploits it as an opportunity.",
        tags: ["Business"],
        authorSlug: "peter-drucker",
        length: 95,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "9aunKqSWDu",
        author: "Dan Gable",
        content:
          "Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.",
        tags: ["Sports", "Competition"],
        authorSlug: "dan-gable",
        length: 115,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "k1TVeBO_5Kh",
        author: "Laurence J. Peter",
        content:
          "An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.",
        tags: ["Business"],
        authorSlug: "laurence-j-peter",
        length: 107,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "l4SIHYrQpX",
        author: "Johann Wolfgang von Goethe",
        content:
          "Knowing is not enough; we must apply. Willing is not enough; we must do.",
        tags: ["Motivational"],
        authorSlug: "johann-wolfgang-von-goethe",
        length: 72,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "_rEPkuDXaWo",
        author: "Casey Stengel",
        content:
          "Finding good players is easy. Getting them to play as a team is another story.",
        tags: ["Sports", "Competition"],
        authorSlug: "casey-stengel",
        length: 78,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "JIk3cbQ8s",
        author: "Michael Jordan",
        content:
          "I've missed more than 9000 shots in my career. I've lost almost 300 games. 26 times, I've been trusted to take the game winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.",
        tags: ["Sports", "Competition", "Famous Quotes"],
        authorSlug: "michael-jordan",
        length: 224,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Yul4uqMwfA1",
        author: "Arnold Palmer",
        content:
          "What other people may find in poetry or art museums, I find in the flight of a good drive.",
        tags: ["Sports", "Competition"],
        authorSlug: "arnold-palmer",
        length: 90,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Aooogq1lu-",
        author: "Theodore Isaac Rubin",
        content:
          "Happiness does not come from doing easy work but from the afterglow of satisfaction that comes after the achievement of a difficult task that demanded our best.",
        tags: ["Business"],
        authorSlug: "theodore-isaac-rubin",
        length: 160,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Wp2A_oOWNEq",
        author: "Muhammad Ali",
        content:
          "It's just a job. Grass grows, birds fly, waves pound the sand. I beat people up.",
        tags: ["Sports"],
        authorSlug: "muhammad-ali",
        length: 80,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "vZ-5DQPCJag",
        author: "George Orwell",
        content:
          "Serious sport has nothing to do with fair play. It is bound up with hatred, jealousy, boastfulness, disregard of all rules and sadistic pleasure in witnessing violence. In other words, it is war minus the shooting.",
        tags: ["Sports"],
        authorSlug: "george-orwell",
        length: 214,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "oPuec6Zts4",
        author: "Seneca the Younger",
        content:
          "If one does not know to which port one is sailing, no wind is favorable.",
        tags: ["Wisdom"],
        authorSlug: "seneca-the-younger",
        length: 72,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "v88YjiHVIp",
        author: "Mia Hamm",
        content:
          "I am building a fire, and everyday I train, I add more fuel. At just the right moment, I light the match.",
        tags: ["Sports", "Competition"],
        authorSlug: "mia-hamm",
        length: 105,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "MNoB9t3dfeS",
        author: "Shaquille O'Neal",
        content:
          "I'm tired of hearing about money, money, money, money, money. I just want to play the game, drink Pepsi, and wear Reebok.",
        tags: ["Sports", "Humorous"],
        authorSlug: "shaquille-o-neal",
        length: 121,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "hZ2TTJbNHgz",
        author: "Mary Kay Ash",
        content:
          "Everyone has an invisible sign hanging from their neck saying, 'Make me feel important.' Never forget this message when working with people.",
        tags: ["Business"],
        authorSlug: "mary-kay-ash",
        length: 140,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "J471lzY_ZWf",
        author: "Jim Bouton",
        content:
          "You spend a good piece of your life gripping a baseball and in the end it turns out that it was the other way around all the time.",
        tags: ["Sports", "Competition"],
        authorSlug: "jim-bouton",
        length: 130,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "VdDvOzQUZ3",
        author: "Ken Venturi",
        content:
          "I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.",
        tags: ["Motivational"],
        authorSlug: "ken-venturi",
        length: 126,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "udbaSw4hIey",
        author: "Harriet Beecher Stowe",
        content:
          "Never give up, for that is just the place and time that the tide will turn.",
        tags: ["Motivational"],
        authorSlug: "harriet-beecher-stowe",
        length: 75,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "GtLeN2MCTvH",
        author: "Nikos Kazantzakis",
        content: "In order to succeed, we must first believe that we can.",
        tags: ["Motivational"],
        authorSlug: "nikos-kazantzakis",
        length: 55,
        dateAdded: "2022-07-06",
        dateModified: "2023-04-14",
      },
      {
        _id: "Yg7xaxX5bj",
        author: "Abraham Lincoln",
        content:
          "Government of the people, by the people, for the people, shall not perish from the Earth.",
        tags: ["History", "Politics", "Famous Quotes"],
        authorSlug: "abraham-lincoln",
        length: 89,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "EhaqmV9Hlb",
        author: "Abraham Lincoln",
        content:
          "The philosophy of the school room in one generation will be the philosophy of government in the next.",
        tags: ["History", "Politics"],
        authorSlug: "abraham-lincoln",
        length: 101,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "-gl-mVVo7R",
        author: "Winston Churchill",
        content:
          "The best argument against democracy is a five-minute conversation with the average voter.",
        tags: ["Humorous", "Politics"],
        authorSlug: "winston-churchill",
        length: 89,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "uSGo8Fn65z",
        author: "Abraham Lincoln",
        content:
          "How many legs does a dog have if you call his tail a leg? Four. Saying that a tail is a leg doesn't make it a leg.",
        tags: ["Truth"],
        authorSlug: "abraham-lincoln",
        length: 114,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "DgPQoKY7nq",
        author: "Winston Churchill",
        content: "History is written by the victors.",
        tags: ["History"],
        authorSlug: "winston-churchill",
        length: 34,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "E9q7mXmEBV",
        author: "Winston Churchill",
        content: "If you're going through hell, keep going.",
        tags: ["Inspirational"],
        authorSlug: "winston-churchill",
        length: 41,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "zbbsaaKwc4",
        author: "Abraham Lincoln",
        content: "No man has a good enough memory to be a successful liar.",
        tags: ["Truth"],
        authorSlug: "abraham-lincoln",
        length: 56,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "JZm3q3illA",
        author: "Winston Churchill",
        content:
          "All the great things are simple, and many can be expressed in a single word: freedom, justice, honor, duty, mercy, hope.",
        tags: ["Social Justice", "Freedom", "History"],
        authorSlug: "winston-churchill",
        length: 120,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "NxfShZ40XpO",
        author: "Abraham Lincoln",
        content:
          "It has been my experience that folks who have no vices have very few virtues.",
        tags: ["Wisdom"],
        authorSlug: "abraham-lincoln",
        length: 77,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "ztXFU0-KGBx",
        author: "Abraham Lincoln",
        content:
          "I have always found that mercy bears richer fruits than strict justice.",
        tags: ["Wisdom"],
        authorSlug: "abraham-lincoln",
        length: 71,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "oek95eM62B",
        author: "Alan Watts",
        content:
          "You and I are all as much continuous with the physical universe as a wave is continuous with the ocean.",
        tags: ["Philosophy"],
        authorSlug: "alan-watts",
        length: 103,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "06AJBdluiw",
        author: "Alan Watts",
        content:
          "You are that vast thing that you see far, far off with great telescopes.",
        tags: ["Philosophy", "Spirituality", "Self"],
        authorSlug: "alan-watts",
        length: 72,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "LGLKYTCTq9",
        author: "Abraham Lincoln",
        content:
          "I am a firm believer in the people. If given the truth, they can be depended upon to meet any national crisis. The great point is to bring them the real facts.",
        tags: ["Politics", "History"],
        authorSlug: "abraham-lincoln",
        length: 159,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "yijmC07Cyu",
        author: "Winston Churchill",
        content: "To improve is to change; to be perfect is to change often.",
        tags: ["Inspirational", "Success"],
        authorSlug: "winston-churchill",
        length: 58,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "nr2GQYc-Hg",
        author: "Abraham Lincoln",
        content: "If I were two-faced, would I be wearing this one?",
        tags: ["Humorous"],
        authorSlug: "abraham-lincoln",
        length: 49,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "HncS4FKWNy",
        author: "Abraham Lincoln",
        content: "I will prepare and some day my chance will come.",
        tags: ["Success"],
        authorSlug: "abraham-lincoln",
        length: 48,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "a86E0FlaTY",
        author: "Alan Watts",
        content:
          "How is it possible that a being with such sensitive jewels as the eyes, such enchanted musical instruments as the ears, and such fabulous arabesque of nerves as the brain can experience itself anything less than a god.",
        tags: ["Philosophy"],
        authorSlug: "alan-watts",
        length: 218,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "LQy9bhVL8Gy",
        author: "Abraham Lincoln",
        content:
          "When I do good I feel good, when I do bad I feel bad, and that's my religion.",
        tags: ["Wisdom", "Character"],
        authorSlug: "abraham-lincoln",
        length: 77,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "Umn2bc4TpG",
        author: "Alan Watts",
        content:
          "But I'll tell you what hermits realize. If you go off into a far, far forest and get very quiet, you'll come to understand that you're connected with everything.",
        tags: ["Nature"],
        authorSlug: "alan-watts",
        length: 161,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "NXFzDIOw6GZ",
        author: "Winston Churchill",
        content:
          "Nothing in life is so exhilarating as to be shot at without result.",
        tags: ["War"],
        authorSlug: "winston-churchill",
        length: 67,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "frhBB_xz6er",
        author: "Winston Churchill",
        content:
          "An appeaser is one who feeds a crocodile, hoping it will eat him last.",
        tags: ["Humorous"],
        authorSlug: "winston-churchill",
        length: 70,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "0c7pkZG_pgE",
        author: "Alan Watts",
        content:
          "And the attitude of faith is the very opposite of clinging to belief, of holding on.",
        tags: ["Faith"],
        authorSlug: "alan-watts",
        length: 84,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "ueNZohx2Vo",
        author: "Winston Churchill",
        content: "Attitude is a little thing that makes a big difference.",
        tags: [],
        authorSlug: "winston-churchill",
        length: 55,
        dateAdded: "2022-03-12",
        dateModified: "2022-03-12",
      },
      {
        _id: "AQpRPKC_9",
        author: "Alan Watts",
        content:
          "The only way to make sense out of change is to plunge into it, move with it, and join the dance.",
        tags: ["Change", "Life"],
        authorSlug: "alan-watts",
        length: 96,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "U1gie7MXOB",
        author: "Abraham Lincoln",
        content: "The ballot is stronger than the bullet.",
        tags: ["Politics", "Famous Quotes"],
        authorSlug: "abraham-lincoln",
        length: 39,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "RsvD5Ur9kY",
        author: "Alan Watts",
        content:
          "I have realized that the past and future are real illusions, that they exist in the present, which is what there is and all there is.",
        tags: ["Time", "Life"],
        authorSlug: "alan-watts",
        length: 133,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "3uAvqPj3dZ",
        author: "Alan Watts",
        content:
          "Never pretend to a love which you do not actually feel, for love is not ours to command.",
        tags: ["Love"],
        authorSlug: "alan-watts",
        length: 88,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "kJ_kF7p8jpS",
        author: "Winston Churchill",
        content:
          "The inherent vice of capitalism is the unequal sharing of blessings; the inherent virtue of socialism is the equal sharing of miseries.",
        tags: ["Politics", "Conservative"],
        authorSlug: "winston-churchill",
        length: 135,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "s2aFAaJuV3",
        author: "Alan Watts",
        content: "I owe my solitude to other people.",
        tags: ["Humorous"],
        authorSlug: "alan-watts",
        length: 34,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "H6E3mARTba",
        author: "Winston Churchill",
        content:
          "The farther backward you can look, the farther forward you can see.",
        tags: ["History"],
        authorSlug: "winston-churchill",
        length: 67,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "_FwZIOj_Tev",
        author: "Alan Watts",
        content:
          "Unless one is able to live fully in the present, the future is a hoax.",
        tags: ["Life", "Future"],
        authorSlug: "alan-watts",
        length: 70,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "u2JiNBARfaw",
        author: "Winston Churchill",
        content:
          "If we open a quarrel between past and present, we shall find that we have lost the future.",
        tags: ["History"],
        authorSlug: "winston-churchill",
        length: 90,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "n_jofZWaKsv",
        author: "Winston Churchill",
        content:
          "We are masters of the unsaid words, but slaves of those we let slip out.",
        tags: ["Wisdom"],
        authorSlug: "winston-churchill",
        length: 72,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "l1KvjJfsFv",
        author: "Alan Watts",
        content:
          "No work or love will flourish out of guilt, fear, or hollowness of heart, just as no valid plans for the future can be made by those who have no capacity for living now.",
        tags: ["Future", "Life"],
        authorSlug: "alan-watts",
        length: 169,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "ubJ9lY7Ark",
        author: "Abraham Lincoln",
        content: "All that I am, or hope to be, I owe to my angel mother.",
        tags: ["Family"],
        authorSlug: "abraham-lincoln",
        length: 55,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "kiih3QxK6xf",
        author: "Alan Watts",
        content:
          "But at any rate, the point is that God is what nobody admits to being, and everybody really is.",
        tags: ["Philosophy", "Self"],
        authorSlug: "alan-watts",
        length: 95,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "VFuYWRR2yM",
        author: "Winston Churchill",
        content:
          "I am an optimist. It does not seem too much use being anything else.",
        tags: [],
        authorSlug: "winston-churchill",
        length: 68,
        dateAdded: "2022-03-12",
        dateModified: "2022-03-12",
      },
      {
        _id: "8-SpjjUpDX",
        author: "Abraham Lincoln",
        content:
          "Always bear in mind that your own resolution to succeed is more important than any other.",
        tags: ["Success"],
        authorSlug: "abraham-lincoln",
        length: 89,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "JFgRzbL3Tw",
        author: "Alan Watts",
        content:
          "The ego is nothing other than the focus of conscious attention.",
        tags: [],
        authorSlug: "alan-watts",
        length: 63,
        dateAdded: "2022-03-12",
        dateModified: "2022-03-12",
      },
      {
        _id: "XgU2ELnEUhe",
        author: "Winston Churchill",
        content:
          "In wartime, truth is so precious that she should always be attended by a bodyguard of lies.",
        tags: ["War", "History"],
        authorSlug: "winston-churchill",
        length: 91,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "tLoJe82KV",
        author: "Winston Churchill",
        content:
          "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.",
        tags: [],
        authorSlug: "winston-churchill",
        length: 111,
        dateAdded: "2022-03-12",
        dateModified: "2022-03-12",
      },
      {
        _id: "e0mfNS8FEa",
        author: "Winston Churchill",
        content: "Russia is a riddle wrapped in a mystery inside an enigma.",
        tags: ["History", "Politics"],
        authorSlug: "winston-churchill",
        length: 57,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "y4rjpOn-joW",
        author: "Winston Churchill",
        content:
          "Courage is rightly esteemed the first of human qualities... because it is the quality which guarantees all others.",
        tags: ["Courage"],
        authorSlug: "winston-churchill",
        length: 114,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "fKsykJ99k",
        author: "Abraham Lincoln",
        content:
          "You can fool all the people some of the time, and some of the people all the time, but you cannot fool all the people all the time.",
        tags: ["Wisdom"],
        authorSlug: "abraham-lincoln",
        length: 131,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "P1qpVayN1l",
        author: "Winston Churchill",
        content:
          "A lie gets halfway around the world before the truth has a chance to get its pants on.",
        tags: ["History", "Politics", "Wisdom"],
        authorSlug: "winston-churchill",
        length: 86,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "quo0uRjP__",
        author: "Abraham Lincoln",
        content:
          "Sir, my concern is not whether God is on our side; my greatest concern is to be on God's side, for God is always right.",
        tags: ["Spirituality", "History"],
        authorSlug: "abraham-lincoln",
        length: 119,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "nZtnCW3_6S",
        author: "Abraham Lincoln",
        content:
          "I am not bound to win, but I am bound to be true. I am not bound to succeed, but I am bound to live by the light that I have. I must stand with anybody that stands right, and stand with him while he is right, and part with him when he goes wrong.",
        tags: ["Inspirational", "History", "Truth"],
        authorSlug: "abraham-lincoln",
        length: 246,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "Bs98LxS5Id",
        author: "Abraham Lincoln",
        content:
          "You cannot escape the responsibility of tomorrow by evading it today.",
        tags: ["History"],
        authorSlug: "abraham-lincoln",
        length: 69,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "bwLNaDverO",
        author: "Winston Churchill",
        content:
          "I am fond of pigs. Dogs look up to us. Cats look down on us. Pigs treat us as equals.",
        tags: ["Humorous", "Famous Quotes"],
        authorSlug: "winston-churchill",
        length: 85,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "ErFK0EPOMHJ",
        author: "Alan Watts",
        content:
          "So then, the relationship of self to other is the complete realization that loving yourself is impossible without loving everything defined as other than yourself.",
        tags: ["Self", "Love"],
        authorSlug: "alan-watts",
        length: 163,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "DNePVvYl4N",
        author: "Alan Watts",
        content:
          "You don't look out there for God, something in the sky, you look in you.",
        tags: ["Spirituality", "Religion"],
        authorSlug: "alan-watts",
        length: 72,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "n4cqmf135I",
        author: "Alan Watts",
        content:
          "Things are as they are. Looking out into it the universe at night, we make no comparisons between right and wrong stars, nor between well and badly arranged constellations.",
        tags: ["Philosophy", "Self"],
        authorSlug: "alan-watts",
        length: 172,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "0UycoCApLT",
        author: "Alan Watts",
        content:
          "Trying to define yourself is like trying to bite your own teeth.",
        tags: ["Humorous"],
        authorSlug: "alan-watts",
        length: 64,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "UfqGrLbrPp",
        author: "Winston Churchill",
        content:
          "You can always count on Americans to do the right thing - after they've tried everything else.",
        tags: ["Humorous", "Politics"],
        authorSlug: "winston-churchill",
        length: 94,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "aMbVRktKAJ",
        author: "Winston Churchill",
        content:
          "Success consists of going from failure to failure without loss of enthusiasm.",
        tags: ["Success"],
        authorSlug: "winston-churchill",
        length: 77,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "S6XZ0bE2Jy",
        author: "Abraham Lincoln",
        content:
          "We the people are the rightful masters of both Congress and the courts, not to overthrow the Constitution but to overthrow the men who pervert the Constitution.",
        tags: ["Politics"],
        authorSlug: "abraham-lincoln",
        length: 160,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "pk0ZBkRYXG",
        author: "Alan Watts",
        content:
          "But the attitude of faith is to let go, and become open to truth, whatever it might turn out to be.",
        tags: ["Faith"],
        authorSlug: "alan-watts",
        length: 99,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "tD2guJsAeO",
        author: "Alan Watts",
        content:
          "We cannot be more sensitive to pleasure without being more sensitive to pain.",
        tags: ["Life", "Pain"],
        authorSlug: "alan-watts",
        length: 77,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "J2YAEeD2ky",
        author: "Winston Churchill",
        content:
          "It is no use saying, 'We are doing our best.' You have got to succeed in doing what is necessary.",
        tags: ["Inspirational", "Success"],
        authorSlug: "winston-churchill",
        length: 97,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "4q4z3dyDhu",
        author: "Winston Churchill",
        content:
          "The truth is incontrovertible. Malice may attack it, ignorance may deride it, but in the end, there it is.",
        tags: ["Truth", "History"],
        authorSlug: "winston-churchill",
        length: 106,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "nldCX72G-j",
        author: "Alan Watts",
        content:
          "To have faith is to trust yourself to the water. When you swim you don't grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.",
        tags: ["Faith"],
        authorSlug: "alan-watts",
        length: 169,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "sXhSm0WMZqL",
        author: "Alan Watts",
        content:
          "Technology is destructive only in the hands of people who do not realize that they are one and the same process as the universe.",
        tags: ["Technology"],
        authorSlug: "alan-watts",
        length: 128,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "6kd9Qs7YQc",
        author: "Abraham Lincoln",
        content: "Most folks are as happy as they make up their minds to be.",
        tags: ["Happiness"],
        authorSlug: "abraham-lincoln",
        length: 58,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "O6hRD-ilnV8",
        author: "Winston Churchill",
        content:
          "I am always ready to learn although I do not always like being taught.",
        tags: ["Humorous"],
        authorSlug: "winston-churchill",
        length: 70,
        dateAdded: "2022-03-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "HMBEfGB94i",
        author: "Henry Ford",
        content:
          "Whether you think you can or you think you can't, you are right.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "henry-ford",
        length: 64,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "aEPNVog6sT",
        author: "Eric Hoffer",
        content:
          "In times of change, learners inherit the earth, while the learned find themselves beautifully equipped to deal with a world that no longer exists.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "eric-hoffer",
        length: 146,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "XNLGqepInX",
        author: "Amy Poehler",
        content: "There's power in looking silly and not caring that you do.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "amy-poehler",
        length: 58,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "2xpHvSOQMD",
        author: "Helmut Schmidt",
        content: "The biggest room in the world is room for improvement.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "helmut-schmidt",
        length: 54,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "QdK00IhCNX",
        author: "Larry Page",
        content:
          "If you're changing the world, you're working on important things. You're excited to get up in the morning.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "larry-page",
        length: 106,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "lJ60rOYWci",
        author: "Neil Gaiman",
        content:
          "The one thing that you have that nobody else has is you. Your voice, your mind, your story, your vision. So write and draw and build and play and dance and live as only you can.",
        tags: ["Famous Quotes", "Inspirational"],
        authorSlug: "neil-gaiman",
        length: 177,
        dateAdded: "2021-06-18",
        dateModified: "2023-04-14",
      },
      {
        _id: "6Kl3UT6ULk",
        content:
          "Wisdom, compassion, and courage are the three universally recognized moral qualities of men.",
        author: "Confucius",
        tags: ["Wisdom"],
        authorSlug: "confucius",
        length: 92,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "wEfrviG0x9r",
        content:
          "With age comes wisdom and a high sex drive. And the wisdom to enjoy it.",
        author: "Amber Valletta",
        tags: ["Wisdom"],
        authorSlug: "amber-valletta",
        length: 71,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "J1amO36TwbX8",
        content: "You can't blame gravity for falling in love.",
        author: "Albert Einstein",
        tags: ["Famous Quotes", "Humorous"],
        authorSlug: "albert-einstein",
        length: 44,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "2wYjTZiTUSgQ",
        content:
          "The things that one most wants to do are the things that are probably most worth doing.",
        author: "Winifred Holtby",
        tags: ["Wisdom"],
        authorSlug: "winifred-holtby",
        length: 87,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "96eV21NlZKJ",
        content: "Make it your habit not to be critical about small things.",
        author: "Edward Everett Hale",
        tags: ["Wisdom"],
        authorSlug: "edward-everett-hale",
        length: 57,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "sTma0kWPt2",
        content: "Friendship, like credit, is highest when it is not used.",
        author: "Elbert Hubbard",
        tags: ["Friendship"],
        authorSlug: "elbert-hubbard",
        length: 56,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "9knYf-nVYu10",
        content:
          "The least of things with a meaning is worth more in life than the greatest of things without it.",
        author: "Carl Jung",
        tags: ["Life"],
        authorSlug: "carl-jung",
        length: 96,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "2xx4dfKrYVRf",
        content:
          "Some people thrive on huge, dramatic change. Some people prefer the slow and steady route. Do what's right for you.",
        author: "Julie Morgenstern",
        tags: ["Wisdom", "Success"],
        authorSlug: "julie-morgenstern",
        length: 115,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "5syS8jEn8m",
        content:
          "When a thing is done, it's done. Don't look back. Look forward to your next objective.",
        author: "George Marshall",
        tags: ["Wisdom"],
        authorSlug: "george-marshall",
        length: 86,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "oT3J6wfjpS",
        content:
          "There is some self-interest behind every friendship. There is no friendship without self-interests. This is a bitter truth.",
        author: "Chanakya",
        tags: ["Friendship"],
        authorSlug: "chanakya",
        length: 123,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "CdL1z3NLSDrN",
        content:
          "Don't talk about what you have done or what you are going to do.",
        author: "Thomas Jefferson",
        tags: ["Wisdom"],
        authorSlug: "thomas-jefferson",
        length: 64,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "6c2h-AtqMj6d",
        content:
          "You can stand tall without standing on someone. You can be a victor without having victims.",
        author: "Harriet Woods",
        tags: ["Wisdom", "Character"],
        authorSlug: "harriet-woods",
        length: 91,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "_XB2MKPzW7dA",
        content:
          "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
        author: "Albert Schweitzer",
        tags: ["Famous Quotes", "Success", "Happiness"],
        authorSlug: "albert-schweitzer",
        length: 125,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "l7UNABW6dA2",
        content: "Silence is the sleep that nourishes wisdom.",
        author: "Francis Bacon",
        tags: ["Wisdom"],
        authorSlug: "francis-bacon",
        length: 43,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "4mPxqSvuiN",
        content:
          "Friendship increases in visiting friends, but in visiting them seldom.",
        author: "Francis Bacon",
        tags: ["Friendship"],
        authorSlug: "francis-bacon",
        length: 70,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "bfpxfIQlqZ_3",
        content:
          "He who controls others may be powerful, but he who has mastered himself is mightier still.",
        author: "Laozi",
        tags: ["Wisdom"],
        authorSlug: "laozi",
        length: 90,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "Oh-e1-oygRPX",
        content: "To be wronged is nothing unless you continue to remember it.",
        author: "Confucius",
        tags: ["Wisdom"],
        authorSlug: "confucius",
        length: 60,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
      {
        _id: "5U3Qdp9L0OId",
        content:
          "Friends are those rare people who ask how we are and then wait to hear the answer.",
        author: "Ed Cunningham",
        tags: ["Friendship"],
        authorSlug: "ed-cunningham",
        length: 82,
        dateAdded: "2021-05-12",
        dateModified: "2023-04-14",
      },
    ],
  },
];
